namespace: sorteio-hml

resources:
- ../../base/ms-sorteio
- ../../base/mfe-sorteio
- ../../base/ingress-hml

images:
- name: ghcr.io/dreis2003/mfe-sorteio
  newName: ghcr.io/dreis2003/mfe-sorteio
  newTag: hml-60a26171b526ca3d97ec7bd12d7f1b634a42c446
- name: ghcr.io/dreis2003/ms-sorteio
  newName: ghcr.io/dreis2003/ms-sorteio
  newTag: hml-a1e24736e725579d07ad6a8971ee92be342472a2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
