namespace: sorteio-hml

resources:
- ../../base/ms-sorteio
- ../../base/mfe-sorteio
- ../../base/ingress-hml

images:
- name: ghcr.io/dreis2003/mfe-sorteio
  newName: ghcr.io/dreis2003/mfe-sorteio
  newTag: hml-cad16fbba60a4ccdcbfdd2ece9655f14768f46ab
- name: ghcr.io/dreis2003/ms-sorteio
  newName: ghcr.io/dreis2003/ms-sorteio
  newTag: hml-83e1c957b663767332a0319656ef0b55b2dbe3ea
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
