namespace: sorteio-hml

resources:
- ../../base/ms-sorteio
- ../../base/mfe-sorteio
- ../../base/ingress-hml

images:
- name: ghcr.io/dreis2003/mfe-sorteio
  newName: ghcr.io/dreis2003/mfe-sorteio
  newTag: hml-7e22b58bcb889bee44acb3da043395ee91cc0a90
- name: ghcr.io/dreis2003/ms-sorteio
  newName: ghcr.io/dreis2003/ms-sorteio
  newTag: hml-cc152c85e2d940fb86dec3b84ff2867351cdb2b2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
