apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ycommunication-hml-ingress
  namespace: ycommunication-hml
spec:
  ingressClassName: traefik
  rules:
    - host: ycomm-hml.yakuzastudio.com.br
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ycommunication-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ycommunication-web
                port:
                  number: 80
