apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: springboot-demo
          image: ghcr.io/dreis2003/springboot-demo-ci:515622f0dd648c563d9cb01bf1415b37d3352aed
          ports:
            - containerPort: 8080