apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sorteio-prd

resources:
- ../../base/ms-sorteio
- ../../base/mfe-sorteio
- ../../base/ingress-prd

images:
- name: ghcr.io/dreis2003/mfe-sorteio
  newName: ghcr.io/dreis2003/mfe-sorteio
  newTag: prd-c06cfb0ef692b34ab7dd71379f90ee1edcaecab6
- name: ghcr.io/dreis2003/ms-sorteio
  newName: ghcr.io/dreis2003/ms-sorteio
  newTag: prd-55e59abb288c9bc8c2773360d091fbdbb586798b

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ms-sorteio
    spec:
      template:
        spec:
          containers:
            - name: ms-sorteio
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prd"
  target:
    kind: Deployment
    name: ms-sorteio
