namespace: ikon-hml

resources:
- namespace.yaml
- ../../base/ms-auth
- ../../base/ms-cadastro-filiados
- ../../base/bff-ikon-brasil
- ../../base/ikon-brasil-web
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/dreis2003/bff-ikon-brasil
  newName: ghcr.io/dreis2003/bff-ikon-brasil
  newTag: hml-b6b3e60589d3b5360ac233f58c8c0b7c58100a82
- name: ghcr.io/dreis2003/ikon-brasil-web
  newName: ghcr.io/dreis2003/ikon-brasil-web
  newTag: hml-ebef7c6f5a4d74a70e761cf792493eca5a34af72
- name: ghcr.io/dreis2003/ms-auth
  newName: ghcr.io/dreis2003/ms-auth
  newTag: hml-51dbc89b09c3e5014d6c76a52c1e9c2856613f44
- name: ghcr.io/dreis2003/ms-cadastro-filiados
  newName: ghcr.io/dreis2003/ms-cadastro-filiados
  newTag: hml-9a3065d0740add8253aa32992f5f770e2920a2f8
