apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-yaml
  namespace: dev

spec:
  replicas: 8

  selector:
    matchLabels:
      app: nginx-yaml

  template:
    metadata:
      labels:
        app: nginx-yaml

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80
