apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ykanban-hml

resources:
- namespace.yaml
- ../../base/ykanban-api
- ../../base/ykanban-web
- ../../base/ingress-hml

images:
- name: ghcr.io/dreis2003/ykanban-backend
  newName: ghcr.io/dreis2003/ykanban-backend
  newTag: hml-latest
- name: ghcr.io/dreis2003/ykanban-frontend
  newName: ghcr.io/dreis2003/ykanban-frontend
  newTag: hml-latest
