apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ykanban-hml

resources:
- namespace.yaml
- ../../base/ykanban-api
- ../../base/ykanban-web
- ../../base/ingress-hml

images:
- name: ghcr.io/dreis2003/ykanban-backend
  newName: ghcr.io/dreis2003/ykanban-backend
  newTag: hml-cbd73f7a35d94874bd941116109cea9fbb4a4667
- name: ghcr.io/dreis2003/ykanban-frontend
  newName: ghcr.io/dreis2003/ykanban-frontend
  newTag: hml-latest

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ykanban-api
    spec:
      template:
        spec:
          containers:
            - name: ykanban-api
              env:
                - name: CORS_ALLOWED_ORIGINS
                  value: "https://ykanban-hml.yakuzastudio.com.br"
  target:
    kind: Deployment
    name: ykanban-api
